specification(1,
[
['Student is an entity type.'],
['Department is an entity type.'],
['Course is an entity type.'],
['Teacher is an entity type.'],
['Enrolment is an entity type.'],
['Section is an entity type.'],
['Student id is of integer data type.'],
['Student name is of string data type.'],
['Department number is of integer data type.'],
['Department name is of string data type.'],
['Teacher id is of integer data type.'],
['Teacher name is of string data type.'],
['Course id is of integer data type.'],
['Course name is of string data type.'],
['Enrolment semester is of integer data type.'],
['Enrolment grade is of string data type.'],
['Section id is of integer data type.'],
['Section name is of string data type.'],
['Student belongs to department.'],
['Department contains student.'],
['Teacher works in department.'],
['Department employs teacher.'],
['Department offers course.'],
['Course is offered by department.'],
['Course is offered in sections.'],
['Teacher teaches student in course.'],
['Enrolment associates "Student belongs to department".'],
['Enrolment associates "Teacher teaches student in course".'],
['Every student belongs to exactly 1 department.'],
['Every department contains 1 or more students.'],
['Every teacher works in exactly 1 department.'],
['Every department contains 1 or more teachers.'],
['Every course is offered by exactly 1 department.'],
['Every department offers 1 or more courses.'],
['Every enrolment includes exactly 1 teacher.'],
['Every enrolment includes exactly 1 student.'],
['Every enrolment includes exactly 1 course.'],
['Every student owns exactly 1 student id and owns exactly 1 student name.'],
['Every teacher owns exactly 1 teacher id and owns exactly 1 teacher name.'],
['Every course owns exactly 1 course id and owns exactly 1 course name.'],
['Every department owns exactly 1 department number and owns exactly 1 department name.'],
['Every enrolment consists of exactly 1 enrolment semester and consists of exactly 1 enrolment grade.'],
['Every section owns exactly 1 section id and owns exactly 1 section name.'],
['Every section is dependent of exactly 1 course.']
]).




