lexicon([cat:noun,wform:['Student'],num:sg,type:entity,arg:A,sem:entity(A,student)]).
lexicon([cat:noun,wform:[student],num:sg,type:const,arg:A,sem:entity(A,student)]).
lexicon([cat:noun,wform:[students],num:pl,type:entity,arg:A,sem:entity(A,student)]).
lexicon([cat:noun,wform:['Program'],num:sg,type:entity,arg:A,sem:entity(A,program)]).
lexicon([cat:noun,wform:[program],num:sg,type:const,arg:A,sem:entity(A,program)]).
lexicon([cat:noun,wform:[programs],num:pl,type:entity,arg:A,sem:entity(A,program)]).
lexicon([cat:noun,wform:['Unit'],num:sg,type:entity,arg:A,sem:entity(A,unit)]).
lexicon([cat:noun,wform:[unit],num:sg,type:const,arg:A,sem:entity(A,unit)]).
lexicon([cat:noun,wform:[units],num:pl,type:const,arg:A,sem:entity(A,unit)]).
lexicon([cat:noun,wform:['Enrollment'],num:sg,type:entity,arg:A,sem:entity(A,enrollment)]).
lexicon([cat:noun,wform:['Student',id],num:sg,type:attribute,dt:integer,arg:A,sem:attribute(A,student_id)]).
lexicon([cat:noun,wform:['Student',name],num:sg,type:attribute,dt:string,arg:A,sem:attribute(A,student_name)]).
lexicon([cat:noun,wform:['Program',id],num:sg,type:attribute,dt:integer,arg:A,sem:attribute(A,program_id)]).
lexicon([cat:noun,wform:['Program',name],num:sg,type:attribute,dt:string,arg:A,sem:attribute(A,program_name)]).
lexicon([cat:noun,wform:['Unit',code],num:sg,type:attribute,dt:integer,arg:A,sem:attribute(A,unit_code)]).
lexicon([cat:noun,wform:['Unit',name],num:sg,type:attribute,dt:string,arg:A,sem:attribute(A,unit_name)]).
lexicon([cat:verb,wform:[is,enrolled,in],num:sg,type:brel,arg:entity(A,student),arg:entity(B,program),sem:relation(entity(A,student),entity(B,program),is_enrolled_in)]).
lexicon([cat:verb,wform:[is,enrolled,by],num:sg,type:brel,arg:entity(A,program),arg:entity(B,student),sem:relation(entity(A,program),entity(B,student),is_enrolled_by)]).
lexicon([cat:verb,wform:[studies],num:sg,type:brel,arg:entity(A,student),arg:entity(B,unit),sem:relation(entity(A,student),entity(B,unit),studies)]).
lexicon([cat:verb,wform:[is,studied,by],num:sg,type:brel,arg:entity(A,unit),arg:entity(B,student),sem:relation(entity(A,unit),entity(B,student),is_studied_by)]).
lexicon([cat:verb,wform:[is,composed,of],num:sg,type:brel,arg:entity(A,program),arg:entity(B,unit),sem:relation(entity(A,program),entity(B,unit),is_composed_of)]).
lexicon([cat:verb,wform:[belongs,to],num:sg,type:brel,arg:entity(A,unit),arg:entity(B,program),sem:relation(entity(A,unit),entity(B,program),belongs_to)]).
