specification(1,
[
['Student',is,an,entity,'.'],
['Program',is,an,entity,'.'],
['Unit',is,an,entity,'.'],
['Student',id,is,of,integer,data,type,'.'],
['Student',name,is,of,string,data,type,'.'],
['No',student,is,a,program,'.'],
['No',student,is,a,unit,'.'],
['No',unit,is,a,program,'.'],
['Every',student,is,enrolled,in,exactly,1,program,'.'],
['Every',program,is,composed,of,some,units,'.'],
['Every',unit,is,studied,by,some,students,'.'],
['Every',unit,is,belongs,to,some,programs,'.'],
['Every',student,possesses,a,student,id,and,possesses,a,student,name,'.'],
['Every',program,possesses,a,program,id,and,possesses,a,program,name,'.'],
['Every',unit,possesses,a,unit,code,and,possesses,a,unit,name,'.'],
['Every',student,studies,at,least,1,and,at,most,4,units,'.']]).

specification(2,
[
['Student',is,an,entity,'.'],
['Program',is,an,entity,'.'],
['Unit',is,an,entity,'.'],
['Enrollment',is,an,entity,'.'],
['Student',id,is,of,integer,data,type,'.'],
['Student',name,is,of,string,data,type,'.'],
['Program',id,is,of,integer,data,type,'.'],
['Program',name,is,of,string,data,type,'.'],
['Unit',code,is,of,integer,data,type,'.'],
['Unit',name,is,of,string,data,type,'.'],
['Enrollment',date,is,of,date,data,type,'.'],
['Student', is, enrolled, in, program, '.'],
['Program', is, enrolled, by, student, '.'],
['Student', studies, unit, '.'],
['Unit', is, studied, by, student, '.'],
['Program', is, composed, of, unit, '.'],
['Unit', belongs, to, program, '.'],
['Enrollment',objectifies,student,is,enrolled,in,program,'.'],
['Every', student, is, enrolled, in, exactly, 1, program,'.'],
['Every', unit, is, studied, by, 1, or, more, student, '.'],
['Every', program, is, enrolled, by, 1, or, more, student,'.'],
['Every', program, is, composed, of, 1, or, more, unit,'.'],
['Every', unit, belongs, to, 1, or, more, program, '.'],
['Every', student, studies, at, least, 1, and, at, most, 4, unit,'.'],
['Every', student, has, exactly, 1, student, id, and, has, exactly, 1, student, name,'.'],
['Every', unit, has, exactly, 1, unit, code, and, has, exactly, 1, unit, name, '.'],
[Every, program, has, exactly, 1, program, id, and, has, exactly, 1, program, name, '.'],
[Every, enrollment, has, exactly, 1, enrollment, date, '.']]).


specification(3,
[
['Student is an entity type.'],
['Program is an entity type.'],
['Unit is an entity type.'],
['Enrollment is an entity type.'],
['Student id is of integer data type.'],
['Student name is of string data type.'],
['Program id is of integer data type.'],
['Program name is of string data type.'],
['Unit code is of integer data type.'],
['Unit name is of string data type.'],
['Enrollment date is of date data type.'],
['Student is enrolled in program.'],
['Program is enrolled by student.'],
['Student studies unit.'],
['Unit is studied by student.'],
['Program is composed of unit.'],
['Unit belongs to program.'],
['Enrollment objectifies "student is enrolled in program".'],
['Every student is enrolled in exactly 4 programs.'],
['Every student studies at least 1 and at most 4 units.'],
['Every unit is studied by 1 or more students.'],
['Every program is enrolled by 1 or more students.'],
['Every program is composed of 1 or more units.'],
['Every unit belongs to 1 or more programs.'],
['Every student has exactly 1 student id and has exactly 1 student name.'],
['Every unit has exactly 1 unit code and has exactly 1 unit name.'],
['Every program has exactly 1 program id and has exactly 1 program name.'],
['Every enrollment has exactly 1 enrollment date.']
]).

specification(4,
[
[ [[entity(C,student)|A]|B]-[A|B] ],
[ [[entity(C,program)|A]|B]-[A|B] ],
[ [[entity(C,unit)|A]|B]-[A|B] ],
[ [[entity(C,enrollment)|A]|B]-[A|B] ],
[ [[attribute(C,student_id)|A]|B]-[A|B] ],
[ [[attribute(C,student_name)|A]|B]-[A|B] ],
[ [[attribute(C,program_id)|A]|B]-[A|B] ],
[ [[attribute(C,program_name)|A]|B]-[A|B] ],
[ [[attribute(C,unit_code)|A]|B]-[A|B] ],
[ [[attribute(C,unit_name)|A]|B]-[A|B] ],
[ [[attribute(C,enrollment_date)|A]|B]-[A|B] ],
[ [[relation(is_enrolled_in,entity(C,student),entity(D,program))|A]|B]-[A|B] ],
[ [[relation(is_enrolled_by,entity(C,program),entity(D,student))|A]|B]-[A|B] ],
[ [[relation(studies,entity(C,student),entity(D,unit))|A]|B]-[A|B] ],
[ [[relation(is_studied_by,entity(C,unit),entity(D,student))|A]|B]-[A|B] ],
[ [[relation(is_composed_of,entity(C,program),entity(D,unit))|A]|B]-[A|B] ],
[ [[relation(belongs_to,entity(C,unit),entity(D,program))|A]|B]-[A|B] ],
[ [[objectify(entity(C,enrollment),relation(is_enrolled_in,entity(D,student),entity(E,program)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,student)==>exists(D,entity(D,program)&min(4):relation(is_enrolled_in,entity(C,student),entity(D,program)):max(4)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,student)==>exists(D,entity(D,unit)&min(1):relation(studies,entity(C,student),entity(D,unit)):max(4)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,unit)==>exists(D,entity(D,student)&min(1):relation(is_studied_by,entity(C,unit),entity(D,student)):max(m)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,program)==>exists(D,entity(D,student)&min(1):relation(is_enrolled_by,entity(C,program),entity(D,student)):max(m)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,program)==>exists(D,entity(D,unit)&min(1):relation(is_composed_of,entity(C,program),entity(D,unit)):max(m)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,unit)==>exists(D,entity(D,program)&min(1):relation(belongs_to,entity(C,unit),entity(D,program)):max(m)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,student)==>exists(D,attribute(D,student_id)&possess(C,D))&exists(E,attribute(E,student_name)&possess(C,E)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,unit)==>exists(D,attribute(D,unit_code)&possess(C,D))&exists(E,attribute(E,unit_name)&possess(C,E)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,program)==>exists(D,attribute(D,program_id)&possess(C,D))&exists(E,attribute(E,program_name)&possess(C,E)))|A]|B]-[A|B] ],
[ [[forall(C,entity(C,enrollment)==>exists(D,attribute(D,enrollment_date)&possess(C,D)))|A]|B]-[A|B] ]
]).

