specification(1,
[
['Student',is,an,entity,'.'],
['Program',is,an,entity,'.'],
['Unit',is,an,entity,'.'],
['Student',id,is,of,integer,data,type,'.'],
['Student',name,is,of,string,data,type,'.'],
['No',student,is,a,program,'.'],
['No',student,is,a,unit,'.'],
['No',unit,is,a,program,'.'],
['Every',student,is,enrolled,in,exactly,1,program,'.'],
['Every',program,is,composed,of,some,units,'.'],
['Every',unit,is,studied,by,some,students,'.'],
['Every',unit,is,belongs,to,some,programs,'.'],
['Every',student,possesses,a,student,id,and,possesses,a,student,name,'.'],
['Every',program,possesses,a,program,id,and,possesses,a,program,name,'.'],
['Every',unit,possesses,a,unit,code,and,possesses,a,unit,name,'.'],
['Every',student,studies,at,least,1,and,at,most,4,units,'.']]).

specification(2,
[
['Student',is,an,entity,'.'],
['Program',is,an,entity,'.'],
['Unit',is,an,entity,'.'],
['Enrollment',is,an,entity,'.'],
['Student',id,is,of,integer,data,type,'.'],
['Student',name,is,of,string,data,type,'.'],
['Program',id,is,of,integer,data,type,'.'],
['Program',name,is,of,string,data,type,'.'],
['Unit',code,is,of,integer,data,type,'.'],
['Unit',name,is,of,string,data,type,'.'],
['Enrollment',date,is,of,date,data,type,'.'],
['Student', is, enrolled, in, program, '.'],
['Program', is, enrolled, by, student, '.'],
['Student', studies, unit, '.'],
['Unit', is, studied, by, student, '.'],
['Program', is, composed, of, unit, '.'],
['Unit', belongs, to, program, '.'],
['Enrollment',objectifies,student,is,enrolled,in,program,'.'],
['Every', student, is, enrolled, in, exactly, 1, program,'.'],
['Every', unit, is, studied, by, 1, or, more, student, '.'],
['Every', program, is, enrolled, by, 1, or, more, student,'.'],
['Every', program, is, composed, of, 1, or, more, unit,'.'],
['Every', unit, belongs, to, 1, or, more, program, '.'],
['Every', student, studies, at, least, 1, and, at, most, 4, unit,'.'],
['Every', student, has, exactly, 1, student, id, and, has, exactly, 1, student, name,'.'],
['Every', unit, has, exactly, 1, unit, code, and, has, exactly, 1, unit, name, '.'],
[Every, program, has, exactly, 1, program, id, and, has, exactly, 1, program, name, '.'],
[Every, enrollment, has, exactly, 1, enrollment, date, '.']]).
